language: cpp
os:
- linux
- osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib
    - build-essential
    - libbluetooth-dev
    - libudev-dev
    - libusb-1.0-0-dev
env:
  matrix:
  - PACKAGER_NODE_VERSION="5.5" PACKAGER_ARCH="amd64" MAIN_BUILD="true"
  - PACKAGER_NODE_VERSION="5.5" PACKAGER_ARCH="386"
matrix:
  exclude:
  - os: osx
    env: PACKAGER_NODE_VERSION="5.5" PACKAGER_ARCH="386"
branches:
  only:
  - "/^v[0-9]/"
before_install:
- PACKAGER_URL="https://meshblu-connector.octoblu.com/tools/packager/latest"
- curl -fsS "${PACKAGER_URL}/travis_install_node.sh" -o /tmp/travis_install_node.sh
- chmod +x /tmp/travis_install_node.sh
- ". /tmp/travis_install_node.sh"
- if [ "$TRAVIS_OS_NAME" == "linux" -a "$MAIN_BUILD" == "true" ]; then export NPM_PUBLISH="true"; fi
install:
- npm install --build-from-source
script:
- npm test
before_deploy:
- npm prune --production
- npm install meshblu-connector-packager
- npm dedupe
- npm install -g flatten-packages
- flatten-packages
- npm run generate:package
- npm run generate:schema
- cp schemas.json deploy
deploy:
- provider: releases
  api_key:
    secure: "dN0lVxcps3TsPCW9koPwoqKGrVKu9tZoYH5pcYGgpQ1PRuICiAlvveMVexueT48+qu4E/2fwS6PV7BbcBSHkKt5/JruONKNYJ6r5cEfuMILOOj/r0Uh/oOJjuNQUhBAYP2UF0USbN4AznJYJGXtVdu2oEjdO6g9euVnouPIobs2N/vd4fpVTY7DtKtTKu7dHNVy8lJ6fuE/T16gb1KhWKhRkPDTm2PGE28vPSxhTLCDoMlhfMIP1ApOtfgDqZmLOjWu2/o2eXye5tvSOYvkvaIz27YNtvZC0U6tcdDtc3zFriozaursion4dW8VKSMizKxt/nAn+XyMYCAmx4GRZz1QCR04L/XPuDWZnwW67FT1DeV/M7mpvc3ox/o/3y/FC+LhxooitQP58KBF7m81GNjdm8LlgZzAK2hfJB8hmYgz1TCgnLNx2YpdQnTxhZ+0Kld2XwJfNQ1Fjs4Rcvw8RmkJT7lMR5z4mHahiN6AXwCnzJHJp8OnIWfOLN3DnTUJ9cBf1dMojoCEAAN0Swkna8WMmh5ANJKJoTY9waPbE2hEI1c3eMx5UXqPRbr5EVahZ7NcQrzhXPwyRdGSR02tTgjVnCQThTHPBKCifQIdvPUhZ9iethRrsZ2kh2TP9cK+SRZf7ixln396eBxp+etmDPTQe8OhaO7Gjn0MwJg74Pcs="
  file_glob: true
  file:
  - "deploy/*"
  skip_cleanup: true
  on:
    tags: true
- provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: "iCJIsJLXZp2O9AggIpKAFb21ipWZtFOnNSaiXvK85oW7f9VNaPgRO5qgWEEJDtYVV61TtyPQG/3pFQWJ6SnOcPoU/r2U6Hs4U+bYo5Fh2WWLzSRomwQEXrjsOzWipjxCWe7hB5Y2SFTajt71/3FJXx/cXJ8pWjq/UDkp3XVNE6sNl/98LoJ5r4DElsPCzuL+eGIAXsVaPLGnXw3wcIWZrXbsflVRgGeRr5+UGKA7ODOxoZ2Ic98co2gma0/9oC+a706UeVURPAA23Pp5RjSzcAjSNY9zzylWSJZB88aN/1P0KJi67HT6VDy+IxHIafX92j7PiYtC0H76IQcTJ2Y900Ql/R4G8D1NE189n6K0EXgveKFefzu7vgX0NYx3sDy0jLd42a3r5BjjMpUnkxVYaWR46i3x4//gZAnsonE9rw7QebIFJwd9UuiMJe4/M9JRtwFRmYi8qi0HOW5/G4vMJvp9qM9BG6LHyN31YlWqY9qOTWhzhZxOY9L8ZyROETXKgpKCDV0arSDPU/63un5mQkHhHieGYU2VN/zkFlH/46mOwTWmXcbXQVLn2228Z78KDYC59FrM1HaWUZmOsKfCFM/KovvhDgjHFgvswuKqaXm6N0zMngeTEMtbZ+eJTrYMgF3wBAbxkWdVXkDdvzc+pCqVguRx4zUd50x4k8OwyqE="
  on:
    tags: true
    condition: "$NPM_PUBLISH = true"
